# Generated by Django 4.0.6 on 2022-08-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_passdb_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passdb',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
