# Generated by Django 4.0.6 on 2022-08-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_passdb_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passdb',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
